# Map every tournament that has tourney_level = 'A' to either an ATP 250 or ATP 500 tournament along with the actual tournament name

tournaments = {
    'Brisbane': ['250', 'Brisbane International'],
    'Hong Kong': ['250', 'Hong Kong Open'],
    'Adelaide': ['250', 'Adelaide International'],
    'Auckland': ['250', 'Auckland Open'],
    'Montpellier': ['250', 'Open Sud de France'],
    'Cordoba': ['250', 'Córdoba Open'],
    'Dallas': ['250', 'Dallas Open'],
    'Marseille': ['250', 'Open 13 Provence'],
    'Delray Beach': ['250', 'Delray Beach Open'],
    'Buenos Aires': ['250', 'Argentina Open'],
    'Rotterdam': ['500', 'Rotterdam Open'],
    'Doha': ['250', 'Qatar Open'],
    'Los Cabos': ['250', 'Los Cabos Open'],
    'Rio De Janeiro': ['250', 'Rio Open'],
    'Acapulco': ['500', 'Mexican Open'],
    'Dubai': ['500', 'Dubai Tennis Championships'],
    'Santiago': ['250', 'Chile Open'],
    'Estoril': ['250', 'Estoril Open'],
    'Houston': ['250', 'U.S. Men\'s Clay Court Championships'],
    'Marrakech': ['250', 'Grand Prix Hassan II'],
    'Barcelona': ['500', 'Barcelona Open'],
    'Munich': ['250', 'BMW Open'],
    'Bucharest': ['250', 'Romanian Open'],
    'Geneva': ['250', 'Geneva Open'],
    'Lyon': ['250', 'Lyon Open'],
    's Hertogenbosch': ['250', 'Libéma Open'],
    'Stuttgart': ['250', 'Stuttgart Open'],
    'Halle': ['500', 'Halle Open'],
    'Queen\'s Club': ['500', 'Queen\'s Club Championships'],
    'Mallorca': ['250', 'Mallorca Championships'],
    'Eastbourne': ['250', 'Eastbourne International'],
    'Gstaad': ['250', 'Swiss Open'],
    'Hamburg': ['500', 'Hamburg Open'],
    'Bastad': ['250', 'Swedish Open'],
    'Newport': ['250', 'Hall of Fame Open'],
    'Atlanta': ['250', 'Atlanta Open'],
    'Kitzbuhel': ['250', 'Austrian Open'],
    'Umag': ['250', 'Croatia Open'],
    'Washington': ['500', 'Washington Open'],
    'Winston-Salem': ['250', 'Winston-Salem Open'],
    'Chengdu': ['250', 'Chengdu Open'],
    'Hangzhou': ['250', 'Hangzhou Open'],
    'Tokyo': ['500', 'Japan Open'],
    'Beijing': ['500', 'China Open'],
    'Almaty': ['250', 'Almaty Open'],
    'Antwerp': ['250', 'European Open'],
    'Stockholm': ['250', 'Stockholm Open'],
    'Basel': ['500', 'Swiss Indoors'],
    'Vienna': ['500', 'Vienna Open'],
    'Belgrade': ['250', 'Belgrade Open'],
    'Metz': ['250', 'Moselle Open']
}